---
- hosts: all
  become: true

  pre_tasks:
    - name: Vars
      ansible.builtin.include_vars: vars.yml

    - name: Install packages
      ansible.builtin.import_tasks: tasks/packages.yml

  tasks:

    - name: Install mango
      ansible.builtin.import_tasks: tasks/mango.yml

    - name: Install unifi
      ansible.builtin.import_tasks: tasks/unifi.yml
      when: unifi_preset.rc == 1
