---

- name: Add mongodb 3.4 apt key
  ansible.builtin.apt_key:
    url: https://www.mongodb.org/static/pgp/server-3.4.asc
    state: present

- name: Add mongodb repo
  ansible.builtin.apt_repository:
    repo: deb https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse
    state: present
    filename: mongodb-org-3.4.list

- name: Run apt cache update & upgrade
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    state: latest

- name: Run apt install mongodb
  ansible.builtin.apt:
    name:
      - mongodb
    state: present
    update_cache: true

- name: Ensure mongo is running
  ansible.builtin.service:
    name: mongodb
    state: started
    enabled: true
