---

- name: Run apt cache update & upgrade
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    state: latest
    upgrade: true

- name: Run apt install packages
  ansible.builtin.apt:
    name:
      - jsvc
      - curl
      - openjdk-8-jre-headless
      - ca-certificates
      - apt-transport-https
    state: present
    update_cache: true

- name: Check unifi install status
  ansible.builtin.command: which tpeap
  failed_when: false
  changed_when: false
  check_mode: false
  register: unifi_preset

- name: Check if reboot required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required
