---

- name: Install unifi from url
  ansible.builtin.apt:
    deb: " {{ unifi_url }} "

- name: Reboot
  ansible.builtin.reboot:
    post_reboot_delay: 30
  when: reboot_required.stat.exists

- name: Get my public IP
  community.general.ipify_facts:
  register: ip

- name: Get url
  ansible.builtin.debug:
    msg: "unifi Controller is running at https://{{ ipify_public_ip }}:8443"
