---

- name: Create directory
  ansible.builtin.file:
    path: "{{ config_dir }}"
    state: directory
    mode: '0755'

- name: Download unifi deb package
  ansible.builtin.get_url:
    url: " {{ unifi_url }} "
    dest: "{{ config_dir }}/unifi_sysvinit_all.deb"

- name: Install unifi deb
  ansible.builtin.apt:
    deb: "{{ config_dir }}/unifi_sysvinit_all.deb"

- name: Reboot
  ansible.builtin.reboot:
    post_reboot_delay: 30
  when: reboot_required.stat.exists

- name: Get my public IP
  community.general.ipify_facts:
  register: ip

- name: Restart service unifi
  ansible.builtin.service:
    name: unifi
    state: restarted

- name: Get url
  ansible.builtin.debug:
    msg: "unifi Controller is running at https://{{ ipify_public_ip }}:8443"
